use std::path::Path;
use crate::runner::materialize::MaterializedCommand;

#[derive(Debug, Clone, Copy)]
pub enum ScriptFlavor { Bash, Powershell }

pub fn render(commands: &[MaterializedCommand], flavor: ScriptFlavor, source: &str) -> String {
    let ts = chrono::Utc::now().to_rfc3339();
    let header = match flavor {
        ScriptFlavor::Bash => format!(
            "#!/usr/bin/env bash\n# Generated by az-plotter v0.1.0 from {source} on {ts}\nset -euo pipefail\n\n",
        ),
        ScriptFlavor::Powershell => format!(
            "# Generated by az-plotter v0.1.0 from {source} on {ts}\n$ErrorActionPreference = 'Stop'\n\n",
        ),
    };
    let body: String = commands.iter()
        .map(|c| format!("# [{}]\n{}\n", c.node_id.display(), shell_words::join(&c.argv)))
        .collect();
    format!("{header}{body}")
}

pub fn write(commands: &[MaterializedCommand], flavor: ScriptFlavor, source: &str, path: &Path) -> std::io::Result<()> {
    std::fs::write(path, render(commands, flavor, source))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Vec<MaterializedCommand> {
        use crate::model::{NodeId, NodeKind, Scope};
        let s = Scope::new("rg");
        vec![
            MaterializedCommand {
                node_id: NodeId::of(NodeKind::Vnet, "v", &s),
                command_id: "c1".into(),
                argv: vec!["az","network","vnet","create","--name","v","--resource-group","rg"].into_iter().map(String::from).collect(),
            },
        ]
    }

    #[test]
    fn bash_script_starts_with_shebang_and_set_e() {
        let s = render(&sample(), ScriptFlavor::Bash, "hub.azp");
        assert!(s.starts_with("#!/usr/bin/env bash"));
        assert!(s.contains("set -euo pipefail"));
        assert!(s.contains("az network vnet create"));
    }

    #[test]
    fn powershell_sets_error_action_preference() {
        let s = render(&sample(), ScriptFlavor::Powershell, "hub.azp");
        assert!(s.contains("$ErrorActionPreference = 'Stop'"));
    }
}
